# Generated by Django 4.2.3 on 2023-07-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Bike_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('model_year', models.DateField()),
                ('model_size', models.CharField(max_length=20)),
                ('reach_mm', models.IntegerField(default=0)),
                ('stack_mm', models.IntegerField(default=0)),
                ('top_tube_effective_mm', models.IntegerField(default=0)),
                ('head_angle_degrees', models.IntegerField(default=0)),
                ('seat_angle_degrees', models.IntegerField(default=0)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_geometry.bike_brand')),
            ],
        ),
    ]
