# Generated by Django 4.2.3 on 2023-07-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_geometry', '0002_remove_bike_model_head_angle_degrees_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bike_Brand',
            new_name='BikeBrand',
        ),
        migrations.RenameModel(
            old_name='Bike_Geometry',
            new_name='BikeGeometry',
        ),
        migrations.RenameModel(
            old_name='Bike_Model',
            new_name='BikeModel',
        ),
    ]
