# Generated by Django 4.2.3 on 2023-07-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_geometry', '0003_rename_bike_brand_bikebrand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='model_year',
        ),
    ]
