# Generated by Django 4.2.3 on 2023-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_geometry', '0005_bikemodel_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikegeometry',
            name='head_angle_degrees',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='seat_angle_degrees',
            field=models.FloatField(default=None),
        ),
    ]
