# Generated by Django 4.2.3 on 2023-07-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_geometry', '0006_alter_bikegeometry_head_angle_degrees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikegeometry',
            name='socks_size',
        ),
        migrations.AddField(
            model_name='bikegeometry',
            name='shock_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='bb_drop_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='bb_height_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='bb_standard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='chainstay_length_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='fork_offset_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='front_center_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='front_travel_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='head_angle_degrees',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='head_tube_length_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='reach_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='rear_travel_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='seat_angle_degrees',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='seat_clamp_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='seat_tube_center_top',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='seatpost_diameter_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='stack_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='standover_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='top_tube_effective_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='trail_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='wheel_size',
            field=models.CharField(blank=True, choices=[('20', '20"'), ('2', '24"'), ('3', '26"'), ('4', '27.5"'), ('5', '29"')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bikegeometry',
            name='wheelbase_mm',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
