# Generated by Django 4.2.3 on 2023-07-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_geometry', '0008_alter_bikegeometry_wheel_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikegeometry',
            old_name='seat_angle_degrees',
            new_name='seat_tube_angle_degrees',
        ),
    ]
